# Generated by Django 2.2.3 on 2019-10-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('vote_average', models.IntegerField()),
                ('overview', models.TextField()),
                ('release_date', models.CharField(max_length=100)),
            ],
        ),
    ]
