# Generated by Django 2.2.3 on 2019-10-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_createlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='vote_average',
            field=models.FloatField(),
        ),
    ]
