# Generated by Django 2.2.3 on 2019-10-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20191027_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='createlist',
            name='recommend_movie_list',
            field=models.CharField(default='', max_length=500),
        ),
    ]
