# Generated by Django 2.2.3 on 2019-10-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_createlist_recommend_movie_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createlist',
            options={'ordering': ('list_name',)},
        ),
    ]
